<a href="https://colab.research.google.com/github/evacs/deep-learning-challenge/blob/main/OptiAlphaSoup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [ ]:
#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
columns_to_drop = ['EIN','NAME']
clean_app_df = application_df.drop(columns_to_drop, axis=1)

In [ ]:
# Determine the number of unique values in each column.
unique_counts = clean_app_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = clean_app_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 528
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_counts = clean_app_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
cutoff = 1
cl_counts_over1 = class_counts[class_counts > cutoff].index
cl_counts_over1.value_counts()

C1000    1
C1800    1
C1250    1
C8200    1
C1238    1
C1278    1
C1235    1
C1237    1
C7210    1
C2400    1
C1720    1
C4100    1
C1257    1
C1600    1
C1260    1
C2710    1
C0       1
C3200    1
C1234    1
C1246    1
C1267    1
C6000    1
C1500    1
C2000    1
C7120    1
C1200    1
C3000    1
C2100    1
C7000    1
C1700    1
C4000    1
C5000    1
C1270    1
C2700    1
C2800    1
C7100    1
C1300    1
C1280    1
C1230    1
C1400    1
C7200    1
C2300    1
C1240    1
C8000    1
C1256    1
dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_counts[class_counts < 1883].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
encoded_df = pd.get_dummies(clean_app_df)
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = encoded_df["IS_SUCCESSFUL"].values
X = encoded_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

<ipython-input-39-8a5cf08a881f>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = encoded_df.drop(["IS_SUCCESSFUL"],1).values

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  81
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer    relu   sigmoid  softmax
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Check the structure of the model
nn.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_26 (Dense)            (None, 81)                9477

 dense_27 (Dense)            (None, 30)                2460

 dense_28 (Dense)            (None, 1)                 31

=================================================================
Total params: 11968 (46.75 KB)
Trainable params: 11968 (46.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
nn1 = tf.keras.models.Sequential()

nn1.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))
nn1.add(tf.keras.layers.BatchNormalization())
nn1.add(tf.keras.layers.Dropout(0.5))

nn1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
nn1.add(tf.keras.layers.BatchNormalization())
nn1.add(tf.keras.layers.Dropout(0.5))

nn1.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model with an adjusted learning rate
nn1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
from keras.callbacks import Callback

# Custom callback to print information every n epochs
class PrintEveryNEpochs(Callback):
    def __init__(self, n=5):
        self.n = n

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.n == 0:
            print(f'Epoch {epoch + 1}: {logs}')

In [ ]:
# Train the model
print_callback = PrintEveryNEpochs(n=5)

fit_model = nn1.fit(X_train_scaled,y_train,epochs=100,verbose = 0,callbacks=[print_callback])

Epoch 5: {'loss': 0.5711205005645752, 'accuracy': 0.7244596481323242}
Epoch 10: {'loss': 0.5647059082984924, 'accuracy': 0.7278416752815247}
Epoch 15: {'loss': 0.5630071759223938, 'accuracy': 0.7292800545692444}
Epoch 20: {'loss': 0.5601526498794556, 'accuracy': 0.7278416752815247}
Epoch 25: {'loss': 0.5614391565322876, 'accuracy': 0.7296687960624695}
Epoch 30: {'loss': 0.5599669218063354, 'accuracy': 0.7287746667861938}
Epoch 35: {'loss': 0.5593804121017456, 'accuracy': 0.7307961583137512}
Epoch 40: {'loss': 0.5566011667251587, 'accuracy': 0.7327787280082703}
Epoch 45: {'loss': 0.5573685169219971, 'accuracy': 0.7318068742752075}
Epoch 50: {'loss': 0.5573447942733765, 'accuracy': 0.7314958572387695}
Epoch 55: {'loss': 0.5571309924125671, 'accuracy': 0.7315347790718079}
Epoch 60: {'loss': 0.5566961765289307, 'accuracy': 0.7322344779968262}
Epoch 65: {'loss': 0.5556826591491699, 'accuracy': 0.7332841157913208}
Epoch 70: {'loss': 0.5563828349113464, 'accuracy': 0.7327398657798767}
Epoch 75: {'loss': 0.5552155375480652, 'accuracy': 0.7322733402252197}
Epoch 80: {'loss': 0.5547456741333008, 'accuracy': 0.7343336939811707}
Epoch 85: {'loss': 0.5544365644454956, 'accuracy': 0.7336339354515076}
Epoch 90: {'loss': 0.5535863637924194, 'accuracy': 0.731301486492157}
Epoch 95: {'loss': 0.5559242367744446, 'accuracy': 0.7329730987548828}
Epoch 100: {'loss': 0.5531595349311829, 'accuracy': 0.7342170476913452}

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5596 - accuracy: 0.7252 - 485ms/epoch - 2ms/step
Loss: 0.5596022605895996, Accuracy: 0.7252478003501892

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

# Train the model
nn2 = Sequential([
    Dense(108, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation = 'sigmoid')
])

nn2.compile(optimizer='adam', loss='binary_crossentropy', metrics=["accuracy"],)

# Create an instance of the custom callback
print_callback = PrintEveryNEpochs(n=5)

nn2.fit(X_train_scaled, y_train, epochs=100, batch_size=32, verbose=0, callbacks=[print_callback])

Epoch 5: {'loss': 0.5453261733055115, 'accuracy': 0.7349556684494019}
Epoch 10: {'loss': 0.5410860776901245, 'accuracy': 0.7375602722167969}
Epoch 15: {'loss': 0.538174569606781, 'accuracy': 0.7390374541282654}
Epoch 20: {'loss': 0.536733865737915, 'accuracy': 0.7402036786079407}
Epoch 25: {'loss': 0.5353376865386963, 'accuracy': 0.7409811615943909}
Epoch 30: {'loss': 0.5338621735572815, 'accuracy': 0.7419530153274536}
Epoch 35: {'loss': 0.5326117873191833, 'accuracy': 0.7415642738342285}
Epoch 40: {'loss': 0.5319870710372925, 'accuracy': 0.7424972653388977}
Epoch 45: {'loss': 0.5316063761711121, 'accuracy': 0.742225170135498}
Epoch 50: {'loss': 0.5298494100570679, 'accuracy': 0.7428860068321228}
Epoch 55: {'loss': 0.5302821397781372, 'accuracy': 0.7430026531219482}
Epoch 60: {'loss': 0.5292971134185791, 'accuracy': 0.7431581616401672}
Epoch 65: {'loss': 0.5289404988288879, 'accuracy': 0.74413001537323}
Epoch 70: {'loss': 0.5282360315322876, 'accuracy': 0.7440522313117981}
Epoch 75: {'loss': 0.527802586555481, 'accuracy': 0.7440910935401917}
Epoch 80: {'loss': 0.5277403593063354, 'accuracy': 0.7440133690834045}
Epoch 85: {'loss': 0.5270547866821289, 'accuracy': 0.7442854642868042}
Epoch 90: {'loss': 0.5262917876243591, 'accuracy': 0.7446353435516357}
Epoch 95: {'loss': 0.5270408987998962, 'accuracy': 0.7444409728050232}
Epoch 100: {'loss': 0.5263912081718445, 'accuracy': 0.7448297142982483}

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5951 - accuracy: 0.7276 - 641ms/epoch - 2ms/step
Loss: 0.5950981974601746, Accuracy: 0.727580189704895

In [ ]:
# Train the model
nn3 = Sequential([
    Dense(108, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation = 'sigmoid')
])

nn3.compile(optimizer='adam', loss='binary_crossentropy', metrics=["accuracy"],)

# Create an instance of the custom callback
print_callback = PrintEveryNEpochs(n=5)

nn3.fit(X_train_scaled, y_train, epochs=100, batch_size=16, verbose=0, callbacks=[print_callback])

Epoch 5: {'loss': 0.54548579454422, 'accuracy': 0.735499918460846}
Epoch 10: {'loss': 0.5407607555389404, 'accuracy': 0.7375602722167969}
Epoch 15: {'loss': 0.5387724041938782, 'accuracy': 0.7389985918998718}
Epoch 20: {'loss': 0.5370612144470215, 'accuracy': 0.7393096089363098}
Epoch 25: {'loss': 0.5353560447692871, 'accuracy': 0.7411755323410034}
Epoch 30: {'loss': 0.5339825749397278, 'accuracy': 0.7412533164024353}
Epoch 35: {'loss': 0.5325624346733093, 'accuracy': 0.7419530153274536}
Epoch 40: {'loss': 0.5323214530944824, 'accuracy': 0.7431581616401672}
Epoch 45: {'loss': 0.5315085053443909, 'accuracy': 0.7426527738571167}
Epoch 50: {'loss': 0.5336436629295349, 'accuracy': 0.742069661617279}
Epoch 55: {'loss': 0.5309848189353943, 'accuracy': 0.7433913946151733}
Epoch 60: {'loss': 0.5294119119644165, 'accuracy': 0.7430415153503418}
Epoch 65: {'loss': 0.5302066206932068, 'accuracy': 0.7430026531219482}
Epoch 70: {'loss': 0.5300479531288147, 'accuracy': 0.7431581616401672}
Epoch 75: {'loss': 0.5285096764564514, 'accuracy': 0.7439356446266174}
Epoch 80: {'loss': 0.5279852747917175, 'accuracy': 0.7437801361083984}
Epoch 85: {'loss': 0.5290407538414001, 'accuracy': 0.7440910935401917}
Epoch 90: {'loss': 0.5272172093391418, 'accuracy': 0.7444409728050232}
Epoch 95: {'loss': 0.5272467136383057, 'accuracy': 0.7442854642868042}
Epoch 100: {'loss': 0.5263364911079407, 'accuracy': 0.7447131276130676}

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn3.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6443 - accuracy: 0.7272 - 461ms/epoch - 2ms/step
Loss: 0.644264817237854, Accuracy: 0.7272303104400635

In [ ]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimization.h5')